skillmatrix/skill/urls.py
from django.urls import path
from skill import views
urlpatterns = [
    path('add_skill/',views.add_skill_matrix, name='add_skill_matrix'),
    # pat/h('view/<int:id>/',views.skill_view,name="view"),
    path('',views.listskill,name="list"),
    


    
]

skillmatrix/skillmatrix/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('skill.urls')),
]

urlpatterns+=static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)

skillmatrix/skill/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class SkillCatogary(models.Model):
    category = models.CharField(max_length=50,null=True, blank=True)
    
    def __str__(self):
        return self.category
    
    
class SkillLevel(models.Model):
    LEVELS = (
        ('', '----Select Skill Level ------'),
        ('Beginner', 'Beginner'),
        ('Intermediate', 'Intermediate'),
        ('Advanced', 'Advanced'),
        ('Intern', 'Intern'),
        ('Expert', 'Expert'),
    )
    level = models.CharField(default='', choices=LEVELS, max_length=12, unique=True)
    
    def __str__(self):
        return self.level
    
    
class Skills(models.Model):
    category=models.ForeignKey(SkillCatogary, on_delete=models.CASCADE)
    name=models.CharField(max_length=50,null=True,blank=True)
    
    def __str__(self):
        return self.name
    

class Skillmatrix(models.Model):
    user=models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)
    skill=models.ForeignKey(Skills, on_delete=models.CASCADE, null=True, blank=True)
    level=models.ForeignKey(SkillLevel,on_delete=models.CASCADE, null=True, blank=True)
    
    def __str__(self):
        return f'{self.user}'
    
    

    

skillmatrix/skill/forms.py
from django.forms import  ModelForm, TextInput, Select,ChoiceField,HiddenInput, Form
from skill.models import Skillmatrix,Skills,SkillCatogary,SkillLevel
from django import forms



class TechForm(Form):

    t_skill = forms.ModelChoiceField(queryset=Skills.objects.filter(category__category='technology'), widget=Select(
                         attrs={'class': "custom-select col-md-4"}), required=False, label='Skill')
    t_level = forms.ModelChoiceField(required=False, queryset=SkillLevel.objects.all(), widget=Select(
                         attrs={'class': "custom-select col-md-4"}), label='Level')
        


  
class FrameworkForm(Form):
    f_skill = forms.ModelChoiceField(queryset=Skills.objects.filter(category__category='framework'), widget=Select(
                         attrs={'class': "custom-select col-md-4"}),required=False, label='Skill')
    f_level = forms.ModelChoiceField(required=False, queryset=SkillLevel.objects.all(), widget=Select(
                         attrs={'class': "custom-select col-md-4"}), label='Level')
 
 
class DatabaseForm(Form):
    
    d_skill = forms.ModelChoiceField(queryset=Skills.objects.filter(category__category='database'), widget=Select(
                         attrs={'class': "custom-select col-md-4"}), required=False, label='Skill')
    d_level = forms.ModelChoiceField(required=False, queryset=SkillLevel.objects.all(), widget=Select(
                         attrs={'class': "custom-select col-md-4"}), label='Level')
    
    
class OSForm(Form):
   
    o_skill = forms.ModelChoiceField(queryset=Skills.objects.filter(category__category='operating system'), widget=Select(
                         attrs={'class': "custom-select col-md-4"}), required=False, label='Skill')
    o_level = forms.ModelChoiceField(required=False, queryset=SkillLevel.objects.all(), widget=Select(
                         attrs={'class': "custom-select col-md-4"}), label='Level')
    
    
    
class WebApiForm(Form):
   
    w_skill = forms.ModelChoiceField(queryset=Skills.objects.filter(category__category='web-api'), widget=Select(
                         attrs={'class': "custom-select col-md-4"}), required=False,label='Skill')
    w_level = forms.ModelChoiceField(required=False, queryset=SkillLevel.objects.all(), widget=Select(
                         attrs={'class': "custom-select col-md-4"}), label='Level')
    
   

skillmatrix/skill/views.py
from django.shortcuts import render,redirect
from skill.models import Skillmatrix, Skills,SkillLevel,SkillCatogary
from django.contrib.auth.models import User
from django.http import HttpResponse
from skill.forms import TechForm,FrameworkForm,DatabaseForm,OSForm,WebApiForm
from django.forms import formset_factory

# Create your views here.
def home(request):
    return HttpResponse("hey hello")


def listskill(request):
    
    s = Skills.objects.all()
    l=SkillLevel.objects.all()
    
    technology=Skillmatrix.objects.filter(skill__category__category="technology")
    framework=Skillmatrix.objects.filter(skill__category__category="framework")
    database=Skillmatrix.objects.filter(skill__category__category="database")
    os=Skillmatrix.objects.filter(skill__category__category="operating system")
    webapi=Skillmatrix.objects.filter(skill__category__category="web api")
    
    
   
    if request.GET.get('level') and  request.GET.get('skill'):
        sk = request.GET.get('skill')
        lev= request.GET.get('level')
        print(lev)
    
       
        
        skills = Skillmatrix.objects.filter(skill=sk,level=lev).order_by('user__username').distinct('user__username')
        data = {'skill':skills, 's':s,'l':l,'technology':technology,'framework':framework,'database':database,'os':os,'webapi':webapi}
        return render(request, 'search.html', data)
    
    if request.GET.get('skill'):
        q = request.GET.get('skill')
        print(q)
     
        skills = Skillmatrix.objects.filter(skill=q).order_by('user__username').distinct('user__username')
        data = {'skill':skills, 's':s,'l':l,'technology':technology,'framework':framework,'database':database,'os':os,'webapi':webapi}
        return render(request, 'search.html', data)
    
    if request.GET.get('level') and request.GET.get:
        q = request.GET.get('level')
        print(q)
     
        skills = Skillmatrix.objects.filter(level=q).order_by('user__username').distinct('user__username')
        data = {'skill':skills, 's':s,'l':l,'technology':technology,'framework':framework,'database':database,'os':os,'webapi':webapi}
        return render(request, 'search.html', data)
    
    
        
    
    skills = Skillmatrix.objects.all().order_by('user__username').distinct('user__username')
    data = {'skill':skills, 's':s,'l':l,'technology':technology,'framework':framework,'database':database,'os':os,'webapi':webapi}
    
    return render(request, 'list_skill.html', data)





def add_skill_matrix(request):
    tech_form_set = formset_factory(TechForm)
    tech_form = tech_form_set()
    
    framework_form_set = formset_factory(FrameworkForm, extra=1)
    framework_form = framework_form_set()
    
    db_form_set = formset_factory(DatabaseForm,extra=1)
    db_form = db_form_set()
    
    os_form_set = formset_factory(OSForm,extra=1)
    os_form = os_form_set()
    
    web_form_set = formset_factory(WebApiForm,extra=1)
    web_form = web_form_set()
    # os_form = OSForm(request.POST or None)
    # webapi_form = WebApiForm(request.POST or None)
    user = request.user
    print(tech_form)
 
    # import pdb; pdb.set_trace()
    if request.method == 'POST':
        tech_form = tech_form_set(request.POST or None)
        framework_form = framework_form_set(request.POST or None)
        db_form = db_form_set(request.POST or None)
        os_form = os_form_set(request.POST or None)
        web_form = web_form_set(request.POST or None)
        
        print(user)
        if tech_form.is_valid() and framework_form.is_valid() and db_form.is_valid() and os_form.is_valid() and web_form.is_valid():
        # or framework_form.is_valid() and db_form.is_valid() and os_form.is_valid() and webapi_form.is_valid():
        # and framework_form.is_valid() and db_form.is_valid() and os_form.is_valid() and webapi_form.is_valid():
            for form in tech_form:
                t_skill = form.cleaned_data.get('t_skill')
                t_level = form.cleaned_data.get('t_level')
                t = Skillmatrix(skill=t_skill, level=t_level, user=user)
                t.save() 
                
            for form in framework_form:
                f_skill = form.cleaned_data.get('f_skill')
                f_level = form.cleaned_data.get('f_level')
                f = Skillmatrix(skill=f_skill, level=f_level, user=user)
                f.save() 
            
            for form in db_form:
                d_skill = form.cleaned_data.get('d_skill')
                d_level = form.cleaned_data.get('d_level')
                d = Skillmatrix(skill=d_skill, level=d_level, user=user)
                d.save() 
                
            for form in os_form:
                
                o_skill = form.cleaned_data.get('o_skill')
                o_level = form.cleaned_data.get('o_level')
                o = Skillmatrix(skill=o_skill, level=o_level, user=user)
                print(o_skill)
                o.save() 
                
            for form in web_form:
                w_skill = form.cleaned_data.get('w_skill')
                w_level = form.cleaned_data.get('w_level')
                w = Skillmatrix(skill=w_skill, level=w_level, user=user)
                w.save() 
                
            else:
                for form in tech_form:
                    print(tech_form.errors)
        return redirect('list')
    
    forms = {'tech_form':tech_form,'framework_form':framework_form,'db_form':db_form,'os_form':os_form,'web_form':web_form}
           
    return render(request, 'add_skill.html', forms)




        
        

skillmatrix/skill/templates/add_skill.html
{% extends "base.html" %}

{% block content %}



    <p id="name"></p>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <h3>Add Skills</h3>

        <div class="container" style="padding:30px;">
            <h3>Add Technology</h3>
            
            {{tech_form.management_data}}
            {% comment %} {% for form in tech_form %} {% endcomment %}

            {% for hidden in tech_form.hidden_fields %}
                {{ hidden }}
            {% endfor %}

            <div class="row" id="formset">
                {{tech_form}}
                <button id="add-form-button">Add Form</button>
            </div>

            {% comment %} {% endfor %} {% endcomment %}
            
        </div>
        
        <div class="container" style="padding:30px;">
            <h3>Add Framework</h3>
            
            {{tech_form.management_data}}
            {% comment %} {% for form in tech_form %} {% endcomment %}

            {% for hidden in framework_form.hidden_fields %}
                {{ hidden }}
            {% endfor %}

            <div class="row">
                {{framework_form}}
            </div>

            {% comment %} {% endfor %} {% endcomment %}
            
        </div>

        <div class="container" style="padding:30px;">
            <h3>Add Database</h3>
            
            {{db_form.management_data}}
            {% comment %} {% for form in tech_form %} {% endcomment %}

            {% for hidden in db_form.hidden_fields %}
                {{ hidden }}
            {% endfor %}

            <div class="row">
                {{db_form}}
            </div>

            {% comment %} {% endfor %} {% endcomment %}
            
        </div>

        <div class="container" style="padding:30px;">
            <h3>Add Operating System</h3>
            
            {{os_form.management_data}}
            {% comment %} {% for form in tech_form %} {% endcomment %}

            {% for hidden in os_form.hidden_fields %}
                {{ hidden }}
            {% endfor %}

            <div class="row">
                {{os_form}}
                
            </div>

            {% comment %} {% endfor %} {% endcomment %}
            
        </div>


        <div class="container" style="padding:30px;">
            <h3>Add WebApi</h3>
            
            {{web_form.management_data}}
            {% comment %} {% for form in tech_form %} {% endcomment %}

            {% for hidden in web_form.hidden_fields %}
                {{ hidden }}
            {% endfor %}

            <div class="row">
                {{web_form}}
            </div>

            {% comment %} {% endfor %} {% endcomment %}
            
        </div>






        
        {% comment %} <div class="container" style="padding:30px;">
            <h3>Add Framework</h3>
            <div class="row">
                <div class="col-md-4">
                    {{framework_form.f_skill.label}}
                    {{framework_form.f_skill}}
                </div>
                <div class="col-md-4">
                    {{framework_form.f_level.label}}
                    {{framework_form.f_level}}
                </div>

            </div>
            
        </div>

        <div class="container" style="padding:30px;">
            <h3>Add Database</h3>
            <div class="row">
                <div class="col-md-4">
                    {{db_form.d_skill.label}}
                    {{db_form.d_skill}}
                </div>
                <div class="col-md-4">
                    {{db_form.d_level.label}}
                    {{db_form.d_level}}
                </div>

            </div>
            
        </div>

        <div class="container" style="padding:30px;">
            <h3>Add Operating System</h3>
            <div class="row">
                <div class="col-md-4">
                    {{os_form.o_skill.label}}
                    {{os_form.o_skill}}
                </div>
                <div class="col-md-4">
                    {{os_form.o_level.label}}
                    {{os_form.o_level}}
                </div>
            </div>
        </div>

        <div class="container" style="padding:30px;" >
            <h3>Add Web Api</h3>
            <div class="row">
                <div class="col-md-4">
                    {{webapi_form.w_skill.label}}
                    {{webapi_form.w_skill}}
                </div>
                <div class="col-md-4">
                    {{webapi_form.w_level.label}}
                    {{webapi_form.w_level}}
                </div>

            </div>
            
        </div>  
        {% endcomment %}
        
        <div class="container" style="padding-top: 35px;" >
            <input name="submit" value="submit" type="submit" class="btn btn-primary" >
        </div>
        <form>
        
        
<script>
    function addForm() {
        // Get the formset prefix and the current number of forms
        var formsetPrefix = document.getElementById("id_form-prefix").value;
        var totalForms = parseInt(document.getElementById("id_form-TOTAL_FORMS").value);
      
        // Create the form element
        var form = document.createElement("form");
        form.setAttribute("id", formsetPrefix + "-" + totalForms);
        form.setAttribute("class", "form-row");
      
        // Add form fields and other content here
      
        // Append the form to the DOM
        var formsetElement = document.getElementById("formset");
        formsetElement.appendChild(form);
      
        // Update the TOTAL_FORMS hidden input
        document.getElementById("id_form-TOTAL_FORMS").value = totalForms + 1;
      }
      
      document.getElementById("add-form-button").addEventListener("click", addForm);
  </script>

        {% endblock content %}

skillmatrix/skill/templates/base.html
<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]>      <html class="no-js"> <!--<![endif]-->
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title> {% block title %}
        
        {% endblock title %} </title>
        <meta name="description" content="">
        {% comment %} <meta name="viewport" content="width=device-width, initial-scale=1"> {% endcomment %}
        <link rel="stylesheet" href="">
        <!-- CSS only -->
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
        <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.13.1/css/jquery.dataTables.css">
       
   <!-- JavaScript Bundle with Popper -->
   <script src="https://code.jquery.com/jquery-3.6.3.js" integrity="sha256-nQLuAZGRRcILA+6dMBOvcRh5Pe310sBpanc6+QBmyVM=" crossorigin="anonymous"></script>
   <script src="https://code.jquery.com/ui/1.13.2/jquery-ui.js" integrity="sha256-xLD7nhI62fcsEZK2/v8LsBcb4lG7dgULkuXoXB/j91c=" crossorigin="anonymous"></script>
   <script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.13.1/js/jquery.dataTables.js"></script>
   <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
   {% comment %} <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script> {% endcomment %}

    </head>
        <body>
            
        {% block content %}
        
        {% endblock content %}
 

    </body>
</html>

skillmatrix/skill/templates/get_category.html
<select name="skill" class="custom-select col-md-2" required="" id="id_skill">
    <option value="" selected="">---------</option>
    
  {% for c in skills %}
    <option value="{{c.id}}">{{c.name}}</option>
  
    {% endfor %}
  </select>

skillmatrix/skill/templates/home.html
<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]>      <html class="no-js"> <!--<![endif]-->
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title></title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="">
        <!-- CSS only -->
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
   <!-- JavaScript Bundle with Popper -->
   <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
   <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
   <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    </head>
    <style>
        body {
            min-height: 100vh;
          
        
           
          }
          
    </style>
    <body>

        <div class="container py-7">
            <header class="text-center text-white">
             
                <a href="https://bootstrapious.com" class="text-white">
                    
                
                </a>
              </p>
            </header>
            <div class="row py-5">
              <div class="col-lg-10 mx-auto">
                <div class="card rounded shadow border-0">
                  <div class="card-body p-5 bg-white rounded">
                    <div class="table-responsive">
                       
                        <div id="example_filter" class="dataTables_filter">
                          <label>Search:<input type="search" class="form-control form-control-sm" placeholder="" aria-controls="example"></label>
                          <button type="button" class="btn btn-primary float-right">ADD</button>
                        </div>
                      <table id="example"  class="table table-striped table-bordered">
                        <thead>
                          <tr>
                            <th>Slno</th>
                            <th>name</th>
                            <th>View</th>
                            
                          </tr>
                        </thead>
                        <tbody>
                            {% for s in skill %}
                            
                          <tr>
                            <td>{{s.user.id}}</td>
                            
                            <td>{{s.user}}</td>

                            <td><button type="button" class="btn btn-success">View</button></td>
                            
                          </tr>
                          
                          {% endfor %}
                          
                        </tbody>
                      </table>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>

          


          <script>
            $(function() {
                $(document).ready(function() {
                  $('#example').DataTable();
                });
              });
              
          </script>
        <!--[if lt IE 7]>
            <p class="browsehappy">You are using an <strong>outdated</strong> browser. Please <a href="#">upgrade your browser</a> to improve your experience.</p>
        <![endif]-->
        
        <script src="" async defer></script>
    </body>
</html>

skillmatrix/skill/templates/list_skill.html
{% extends 'base.html' %}
{% block content %}

<div class="container py-7">
    <header class="text-center text-white">
         
            
                
            
            </a>
          </p>
        </header>


        <div class="row py-5">
          <div class="col-lg-10 mx-auto">
            <div class="card rounded shadow border-0">
              <div class="card-body p-5 bg-white rounded">
                <div class="table-responsive">
                   


                    <div id="example_filter" class="dataTables_filter">
                     
                      <a href="{% url 'add_skill_matrix' %}" class="btn btn-primary float-right">ADD</a>
                    </div>
                     <form action="" >

                       <div class="form-control">
                         
                         <select id="skill" name="skill" class="custom-select col-md-2" >
                          <option value="{% if request.GET.skill %}{{ request.GET.skill }}{% else %}{% endif %}" selected>{% if request.GET.skill %}{{ request.GET.skill }}{% else %}Select Skill{% endif %}</option>
                           {% for sk in s %}
                           <option value="{{sk.id}}">{{sk.name}}</option>
                           {% endfor %}
                           
                          </select>

                          <select id="level" name="level" class="custom-select col-md-2" >
                            <option value="{% if request.GET.level %}{{ request.GET.level }}{% else %}{% endif %}" selected>{% if request.GET.level %}{{ request.GET.level }}{% else %}Select Level{% endif %}</option>
                             {% for lk in l %}
                             <option value="{{lk.id}}">{{lk.level}}</option>
                             {% endfor %}
                             
                            </select>
                          <button type="submit" name="filter" class="btn btn-success col-md-2">
                             Filter
                          </button>
                          
                        </div>
                      </form>
                        
                  <table id="example"  class="table table-striped table-bordered">
                      <thead>
                          <tr>
                        <th>Slno</th>
                        <th>name</th>
                        <th>Technology</th>
                        <th>Framework</th>
                        <th>Database</th>
                        <th>Operating System</th>
                        <th>Web Api</th>
                        
                      </tr>
                    </thead>
                    <tbody>
                        {% for s in skill %}
                        
                      <tr>
                        <td>{{forloop.counter}}</td>
                        
                        <td>{{s.user}}</td>
 
                        <td> 
                          <table>
                           
                            <tr> <th> Technology Name </th> <th> Technology level </th> </tr>
                            {% for t in technology  %}
                            {% if t.user == s.user %}
                            <tr> <td>{{t.skill.name}} </td><td> {{t.level.level}} </td> </tr>
                            {% endif %}
                            {% endfor %}
                            </table>
                        </td>

                        <td> 
                          <table>
                           
                            <tr> <th> Framework Name </th> <th> Framework level </th> </tr>
                            {% for f in framework  %}
                            {% if f.user == s.user %}
                            <tr> <td> {{f.skill.name}} </td><td> {{f.level.level}} </td> </tr>
                            {% endif %}
                            {% endfor %}
                            </table>
                        </td>

                        <td> 
                          <table>
                           
                            <tr> <th> Database Name </th> <th> Database level </th> </tr>
                            {% for d in database  %}
                            {% if d.user == s.user %}
                            <tr> <td> {{d.skill.name}} </td><td> {{d.level.level}} </td> </tr>
                            {% endif %}
                            {% endfor %}
                            </table>
                        </td>

                        <td> 
                          <table>
                           
                            <tr> <th> Operating system Name </th> <th> Operating system level </th> </tr>
                            {% for o in os  %}
                            {% if o.user == s.user %}
                            <tr> <td> {{o.skill.name}} </td><td> {{o.level.level}} </td> </tr>
                            {% endif %}
                            {% endfor %}
                            </table>
                        </td>
                        
                        <td> 
                          <table>
                           
                            <tr> <th> WebApi Name </th> <th> webApi level </th> </tr>
                            {% for w in webapi  %}
                            {% if w.user == s.user %}
                            <tr> <td> {{w.skill.name}} </td><td> {{w.level.level}} </td> </tr>
                            {% endif %}
                            {% endfor %}
                            </table>
                        </td>

                      </tr>
                      
                      {% endfor %}
                      
                    </tbody>
                  </table>
                </div>
              </div>
            </div>
        </div>
        </div>
      </div>

      

      
      <script>
        $(function() {
            $(document).ready(function() {
              $('#example').DataTable();
            });
    
             $('#example-getting-started').multiselect();
 

          });
          
      </script>
    <!--[if lt IE 7]>
        <p class="browsehappy">You are using an <strong>outdated</strong> browser. Please <a href="#">upgrade your browser</a> to improve your experience.</p>
    <![endif]-->
    
    <script src="" async defer></script>
    
    {% endblock content %}

skillmatrix/skill/templates/view.html
{% extends "base.html" %}

{% block content %}


<div class="container py-7">
        <header class="text-center text-white">
         
 
          </p>
        </header>
        <div class="row py-5">
          <div class="col-lg-10 mx-auto">
            <div class="card rounded shadow border-0">
              <div class="card-body p-5 bg-white rounded">
                <div class="table-responsive">
                   
                    <div id="example_filter" class="dataTables_filter">
                   
                      <button type="button" class="btn btn-primary float-right">ADD</button>
                    </div>
                    <h1>{% for s in skill  %}
                        {% if forloop.counter == 1 %}
                        {{s.user}}
                        {% endif %}
                        {% endfor %}</h1>
                  <table id="example"  class="table table-striped table-bordered">
                    <thead>
                      <tr>
                        
                        <th>SLNO</th>
                        <th>category</th>
                        <th>skill name</th>
                        <th>skill level</th>
                        
                      </tr>
                    </thead>
                    <tbody>
                        
                        {% for s in skill %}
                      <tr>
                        
                        <td>{{forloop.counter}}</td>
                        <td>{{s.skill.category.category}}</td>
                        <td>{{s.skill.name}}</td>
                        
                        <td>{{s.level}}</td>

                        

                        
                        
                      </tr>
                      {% endfor %}
                      
                      
                      
                    </tbody>
                  </table>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>

      


      <script>
        $(function() {
            $(document).ready(function() {
              $('#example').DataTable();
            });
          });
      </script>
    <!--[if lt IE 7]>
        <p class="browsehappy">You are using an <strong>outdated</strong> browser. Please <a href="#">upgrade your browser</a> to improve your experience.</p>
    <![endif]-->
    
    <script src="" async defer></script>

          {% endblock content %}